const DAYS=["Lundi","Mardi","Mercredi","Jeudi","Vendredi","Samedi","Dimanche"];
const MEALS=["Petit déjeuner","Gouter Matin","Repas","Gouter Soir","Diner","Dessert"];
const CATS=["Fruits & légumes","Viandes & poissons","Produits laitiers","Épicerie","Boulangerie","Surgelés","Boissons","Autres"];
const $=id=>document.getElementById(id);
let state={recipes:[],agenda:{},extras:[],shopping:[]}, current=null, draft=[];
function emptyAgenda(){const a={};DAYS.forEach(d=>{a[d]={};MEALS.forEach(m=>a[d][m]=null)});return a}
function uid(){return crypto.randomUUID?crypto.randomUUID():Date.now()+"-"+Math.random()}
function toast(t){$("toast").textContent=t;$("toast").classList.add("show");setTimeout(()=>$("toast").classList.remove("show"),1600)}
function dbOpen(){return new Promise((ok,ko)=>{const r=indexedDB.open("RecipePlannerDB",1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains("state"))r.result.createObjectStore("state")};r.onsuccess=()=>ok(r.result);r.onerror=()=>ko(r.error)})}
async function dbGet(){const db=await dbOpen();return new Promise((ok,ko)=>{const r=db.transaction("state","readonly").objectStore("state").get("app");r.onsuccess=()=>ok(r.result);r.onerror=()=>ko(r.error)})}
async function save(){const db=await dbOpen();return new Promise((ok,ko)=>{const tx=db.transaction("state","readwrite");tx.objectStore("state").put(state,"app");tx.oncomplete=ok;tx.onerror=()=>ko(tx.error)})}
async function samples(){const r=await fetch("data/recettes.json");state={recipes:await r.json(),agenda:emptyAgenda(),extras:[],shopping:[]};await save()}
async function init(){const s=await dbGet();if(s)state=s;else await samples();state.agenda ||= emptyAgenda();state.extras ||= [];state.shopping ||= [];fill();buildAgenda();renderAgenda();renderExtras();renderShop();show(match()[0]||null)}
function fill(){const origins=[...new Set(state.recipes.map(r=>r.origine))].sort();$("origin").innerHTML="<option>Peu importe</option>"+origins.map(x=>`<option>${x}</option>`).join("");["mc","ic"].forEach(id=>$(id).innerHTML=CATS.map(x=>`<option>${x}</option>`).join(""));$("dDay").innerHTML=DAYS.map(x=>`<option>${x}</option>`).join("");$("dMeal").innerHTML=MEALS.map(x=>`<option>${x}</option>`).join("")}
function match(){const o=$("origin").value,t=$("type").value,tf=$("time").value;return state.recipes.filter(r=>{const ex=r.type==="Extra";if(t==="Extra"){if(!ex)return false}else{if(ex)return false;if(t!=="Peu importe"&&r.type!==t)return false}if(o!=="Peu importe"&&r.origine!==o)return false;const n=+r.temps;if(tf==="lt20"&&n>=20)return false;if(tf==="20-40"&&!(n>=20&&n<=40))return false;if(tf==="40-60"&&!(n>40&&n<=60))return false;if(tf==="gt60"&&n<=60)return false;return true})}
function show(r){current=r;if(!r){$("rname").textContent="Aucune recette";$("rmeta").textContent="";$("badge").textContent="—";return}$("rname").textContent=r.nom;$("badge").textContent=r.type;$("rmeta").textContent=`${r.origine} • ${r.temps} min • ${+$("people").value||1} personne(s)`;$("addAgenda").classList.toggle("hidden",r.type==="Extra");$("addExtra").classList.toggle("hidden",r.type!=="Extra")}
function buildAgenda(){const b=$("agendaTable").querySelector("tbody");b.innerHTML="";MEALS.forEach(m=>{const tr=document.createElement("tr"),th=document.createElement("th");th.textContent=m;tr.appendChild(th);DAYS.forEach(d=>{const td=document.createElement("td");td.dataset.day=d;td.dataset.meal=m;td.onclick=async()=>{if(state.agenda[d][m]){state.agenda[d][m]=null;await save();renderAgenda()}};tr.appendChild(td)});b.appendChild(tr)})}
function renderAgenda(){document.querySelectorAll("#agendaTable td").forEach(td=>{const e=state.agenda[td.dataset.day][td.dataset.meal];td.className=e?"filled":"";td.innerHTML=e?`${e.recipe.nom}<small>${e.people} pers.</small>`:"—"})}
function renderExtras(){const e=$("extras");e.innerHTML="";if(!state.extras.length){e.innerHTML="<p>Aucun Extra.</p>";return}state.extras.forEach((x,i)=>{const d=document.createElement("div");d.className="row";d.innerHTML=`<span>${x.recipe.nom} - ${x.people} personnes</span>`;const b=document.createElement("button");b.textContent="Retirer";b.onclick=async()=>{state.extras.splice(i,1);await save();renderExtras()};d.appendChild(b);e.appendChild(d)})}
function genShop(){const m=new Map();const add=e=>{const ratio=e.people/e.recipe.base;e.recipe.ingredients.forEach(i=>{const k=`${i.nom.toLowerCase()}|${i.unite}|${i.categorie}`;if(!m.has(k))m.set(k,{id:uid(),nom:i.nom,unite:i.unite,categorie:i.categorie||"Autres",quantite:0,checked:false});m.get(k).quantite+=+i.quantite*ratio})};DAYS.forEach(d=>MEALS.forEach(meal=>{const e=state.agenda[d][meal];if(e)add(e)}));state.extras.forEach(add);state.shopping=[...m.values()].map(x=>({...x,quantite:Math.ceil(x.quantite)}));save();renderShop()}
function renderShop(){const e=$("shoppingList");e.innerHTML="";CATS.forEach(c=>{const items=state.shopping.filter(x=>x.categorie===c);if(!items.length)return;const s=document.createElement("div");s.className="shopcat";s.innerHTML=`<h3>${c}</h3>`;items.forEach(it=>{const r=document.createElement("div");r.className="shoprow"+(it.checked?" checked":"");const cb=document.createElement("input");cb.type="checkbox";cb.checked=it.checked;cb.onchange=async()=>{it.checked=cb.checked;await save();renderShop()};const q=document.createElement("input");q.type="number";q.value=it.quantite;q.onchange=async()=>{it.quantite=+q.value||0;await save()};const p=document.createElement("span");p.className="prod";p.textContent=`${it.unite} — ${it.nom}`;const del=document.createElement("button");del.textContent="×";del.onclick=async()=>{state.shopping=state.shopping.filter(x=>x.id!==it.id);await save();renderShop()};r.append(cb,q,p,del);s.appendChild(r)});e.appendChild(s)});if(!state.shopping.length)e.innerHTML="<p>Liste vide.</p>"}
document.querySelectorAll("nav button").forEach(b=>b.onclick=()=>{document.querySelectorAll("nav button").forEach(x=>x.classList.toggle("active",x===b));document.querySelectorAll(".page").forEach(p=>p.classList.toggle("active",p.id===b.dataset.tab))});
$("find").onclick=()=>show(match()[0]||null);$("random").onclick=()=>{const a=match();show(a.length?a[Math.floor(Math.random()*a.length)]:null)};["origin","people","time","type"].forEach(id=>$(id).onchange=()=>show(match()[0]||null));
$("addAgenda").onclick=()=>current&&$("dlg").showModal();$("dOk").onclick=async e=>{e.preventDefault();const d=$("dDay").value,m=$("dMeal").value;state.agenda[d][m]={recipe:current,people:+$("people").value||1};await save();renderAgenda();$("dlg").close();toast("Ajouté")};
$("addExtra").onclick=async()=>{if(!current||current.type!=="Extra")return;state.extras.push({recipe:current,people:+$("people").value||1});await save();renderExtras();toast("Extra ajouté")};
$("clearAgenda").onclick=async()=>{state.agenda=emptyAgenda();state.extras=[];await save();renderAgenda();renderExtras()};
$("genShop").onclick=genShop;
$("madd").onclick=async()=>{const n=$("mp").value.trim();if(!n)return;state.shopping.push({id:uid(),nom:n,quantite:+$("mq").value||1,unite:$("mu").value,categorie:$("mc").value,checked:false});$("mp").value="";await save();renderShop()};
$("iadd").onclick=()=>{const n=$("in").value.trim();if(!n)return;draft.push({nom:n,quantite:+$("iq").value||1,unite:$("iu").value,categorie:$("ic").value});$("in").value="";renderDraft()};
function renderDraft(){$("draft").innerHTML="";draft.forEach((x,i)=>{const d=document.createElement("div");d.className="row";d.innerHTML=`<span>${x.quantite} ${x.unite} — ${x.nom} — ${x.categorie}</span>`;const b=document.createElement("button");b.textContent="Retirer";b.onclick=()=>{draft.splice(i,1);renderDraft()};d.appendChild(b);$("draft").appendChild(d)})}
$("saveRecipe").onclick=async()=>{const nom=$("nn").value.trim(),origine=$("no").value.trim();if(!nom||!origine||!draft.length){toast("Complète la recette");return}state.recipes.push({id:uid(),nom,origine,type:$("nt").value,temps:+$("ntime").value||0,base:Math.max(1,+$("nbase").value||1),ingredients:[...draft]});draft=[];renderDraft();fill();await save();toast("Recette enregistrée")};
$("export").onclick=()=>{const blob=new Blob([JSON.stringify({format:"RecipePlannerBackup",version:1,state},null,2)],{type:"application/json"}),a=document.createElement("a"),d=new Date();a.href=URL.createObjectURL(blob);a.download=`RecipePlanner_backup_${String(d.getDate()).padStart(2,"0")}-${String(d.getMonth()+1).padStart(2,"0")}-${d.getFullYear()}.json`;a.click();URL.revokeObjectURL(a.href)};
$("import").onchange=async e=>{try{const j=JSON.parse(await e.target.files[0].text()),s=j.state||j;if(!Array.isArray(s.recipes))throw 0;state={recipes:s.recipes,agenda:s.agenda||emptyAgenda(),extras:s.extras||[],shopping:s.shopping||[]};await save();fill();renderAgenda();renderExtras();renderShop();show(match()[0]||null);toast("Sauvegarde restaurée")}catch{toast("JSON invalide")}e.target.value=""};
if("serviceWorker" in navigator)addEventListener("load",()=>navigator.serviceWorker.register("./service-worker.js"));
init();
